# Generated by Django 4.0.4 on 2022-05-05 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('code', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('dateCreation', models.DateField()),
                ('solde', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl', to='dabih_yassine.client')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('numeroOperation', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('dateOperation', models.DateField()),
                ('montant', models.BooleanField()),
                ('type', models.CharField(max_length=255)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compte', to='dabih_yassine.compte')),
            ],
        ),
    ]
