# Generated by Django 4.0.4 on 2022-05-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabih_yassine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='montant',
            field=models.FloatField(),
        ),
    ]
