# Generated by Django 4.0.4 on 2022-05-06 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dabih_yassine', '0002_alter_operation_montant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='type',
        ),
    ]
