# Generated by Django 4.0.4 on 2022-05-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabih_yassine', '0003_remove_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('versement', 'Versement'), ('retrait', 'Retrait')], default='versement', max_length=9),
        ),
        migrations.AlterField(
            model_name='compte',
            name='solde',
            field=models.FloatField(),
        ),
    ]
