# Generated by Django 4.0.4 on 2022-05-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabih_yassine', '0004_operation_type_alter_compte_solde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
