# Generated by Django 4.0.4 on 2022-05-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabih_yassine', '0005_alter_compte_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
